export { default as LoginPage } from "./AuthPages/LoginPage.tsx"
export { default as RegisterPage } from "./AuthPages/RegisterPage.tsx"
export { default as HomePage } from "./HomePage.tsx"
export { default as ProductsPage } from "./ProductsPage.tsx"
export { default as ProductPage } from "./ProductPage.tsx"